import Joi from 'joi';
export const StudentSchemaValidation = Joi.object({
  id: Joi.string(),
  name: {
    firstName: Joi.string().max(20).required(),
    middleName: Joi.string().max(20),
    lastName: Joi.string().max(20).required(),
  },
  gender: Joi.string().required().valid('male', 'female', 'other'),
  dateOfBirth: Joi.string().required(),
  email: Joi.string().email().required(),
  avatar: Joi.string(),
  contactNo: Joi.string().required(),
  emergencyContactNo: Joi.string().required(),
  bloodGroup: Joi.string().valid(
    'A+',
    'A-',
    'B+',
    'B-',
    'O+',
    'O-',
    'AB+',
    'AB-',
  ),
  permanentAddress: Joi.string().required(),
  presentAddress: Joi.string().required(),
  guardian: {
    fatherName: Joi.string().required(),
    fatherOccupation: Joi.string().required(),
    fatherContactNo: Joi.string().required(),
    motherName: Joi.string().required(),
    motherOccupation: Joi.string().required(),
    motherContactNo: Joi.string().required(),
  },
  localGuardian: {
    name: Joi.string().required(),
    occupation: Joi.string().required(),
    contactNo: Joi.string().required(),
  },
  isActive: Joi.string().required().valid('active', 'blocked'),
});
